"""
Import stage 2: reading a paper from the PDF's own text layer (app/text_extract.py) and choosing between that and OCR.

The PDFs here are generated by tests/pdfmaker.py, so every expected value is known exactly. The real-file check on the
UPPCS Polity test is in test_real_paper.py (slow).
"""
import itertools
import os

import pytest

from app import models, text_extract as te
from pdfmaker import PAGE_H, PAGE_W, flow, make_pdf
from conftest import blank_pdf_bytes

_ref = itertools.count(1)                       # every generated paper is a different file (uploads refuse exact duplicates)
COLUMN_LINES = 25
LEFT_X, RIGHT_X = 50, 330                       # gutter between 290 and 330


def question_lines(n: int, answer: str | None = "ABCD", explanation: bool = True, unclear: bool = False):
    """One question as printed: numbered statements inside it, options two to a line, then answer and explanation."""
    letter = "ABCD"[(n - 1) % 4]
    lines = [
        f"{n}. Consider the following statements about item {n}:",
        f"1. First statement about item {n}.",
        f"2. Second statement about item {n},",
        "which continues on a second line.",
        "Which of the statements given above is correct?",
        "(a) 1 only (b) 2 only",
        "(c) Both 1 and 2 (d) Neither 1 nor 2",
    ]
    if answer is not None:
        lines.append(f"Answer: ({letter.lower()}b)" if unclear else f"Answer-({letter.lower()})" if n % 2 else f"Answer: ({letter.lower()})")
        if explanation:
            lines += [f"Explanation for item {n} is here", "and it wraps as well."]
    return lines


def paper_pdf(count=20, with_answers=True, **kw) -> bytes:
    """Cover page + two-column pages with a header that crosses the gutter, a footer, and a giant watermark."""
    cover, _ = flow(["Instructions", "1. Answer all questions.", "2. Each question has four options.",
                     "3. There is negative marking.", f"Reference {next(_ref)}"], 60, 100)
    body_lines: list[str] = []
    for n in range(1, count + 1):
        body_lines += question_lines(n, "ABCD" if with_answers else None, **kw)
    slots = [(page, col) for page in range(1, 40) for col in (0, 1)]
    pages: dict[int, list] = {}
    for i in range(0, len(body_lines), COLUMN_LINES):
        page, col = slots[i // COLUMN_LINES]
        items, _ = flow(body_lines[i:i + COLUMN_LINES], LEFT_X if col == 0 else RIGHT_X, 70)
        pages.setdefault(page, []).extend(items)
    out = [cover]
    for page in sorted(pages):
        out.append(pages[page]
                   + [(180, 25, 9, "Sectional Test 7: Indian Polity Series A")]                # crosses the gutter
                   + [(50, 810, 9, "https://example.org/join"), (400, 810, 9, f"Page {page}")]
                   + [(150, 400, 110, "WMARK")])                                                # the giant watermark
    return make_pdf(out)


@pytest.fixture()
def pdf_path(tmp_path):
    def write(data: bytes, name="paper.pdf"):
        path = tmp_path / name
        path.write_bytes(data)
        return str(path)
    return write


def read(pdf_path, data, layout="auto"):
    path = pdf_path(data)
    images = os.path.join(os.path.dirname(path), "images")
    return te.extract_questions(path, images, layout=layout), images


# --------------------------------------------------------------------------- is there a text layer?

def test_a_generated_text_pdf_has_a_text_layer_and_a_blank_one_does_not(pdf_path):
    assert te.has_text_layer(pdf_path(paper_pdf(count=6)))
    assert not te.has_text_layer(pdf_path(blank_pdf_bytes(), "blank.pdf"))


def test_a_pdf_with_only_a_page_number_is_not_a_text_pdf(pdf_path):
    scan_like = make_pdf([[(280, 800, 9, "1")], [(280, 800, 9, "2")], [(280, 800, 9, "3")]])
    assert not te.has_text_layer(pdf_path(scan_like))


# --------------------------------------------------------------------------- reading a two-column paper

def test_every_question_is_found_in_order_across_columns_and_pages(pdf_path):
    (questions, warnings), _ = read(pdf_path, paper_pdf(20))
    assert warnings == []
    assert [q["question_number"] for q in questions] == list(range(1, 21))
    assert all(q["page_number"] >= 2 for q in questions)                  # the cover page holds no questions


def test_statements_inside_a_question_are_not_taken_for_questions(pdf_path):
    (questions, _), _ = read(pdf_path, paper_pdf(8))
    q = questions[4]                                                        # question 5
    assert q["text"].startswith("Consider the following statements about item 5:")
    assert "1. First statement about item 5." in q["text"] and "2. Second statement about item 5, which continues on a second line." in q["text"]
    assert q["text"].endswith("Which of the statements given above is correct?")
    assert len(questions) == 8


def test_options_are_split_even_two_to_a_line(pdf_path):
    (questions, _), _ = read(pdf_path, paper_pdf(4))
    assert [(q["option_a"], q["option_b"], q["option_c"], q["option_d"]) for q in questions] == \
        [("1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2")] * 4
    assert all(q["flags"] == [] for q in questions)


def test_the_cover_page_instructions_are_skipped(pdf_path):
    (questions, _), _ = read(pdf_path, paper_pdf(6))
    assert not any("Answer all questions" in q["text"] or "negative marking" in q["text"] for q in questions)
    assert questions[0]["question_number"] == 1 and questions[0]["text"].startswith("Consider the following statements about item 1")


def test_the_watermark_headers_and_footers_do_not_leak_into_the_text(pdf_path):
    (questions, _), _ = read(pdf_path, paper_pdf(20))
    everything = " ".join(q["text"] + q["option_d"] + (q["explanation"] or "") for q in questions)
    for junk in ("WMARK", "Sectional Test 7", "example.org", "Page 2", "Page 3"):
        assert junk not in everything, junk
    assert all(not q["option_d"].endswith(("Page 2", "Page 3")) for q in questions)


def test_a_small_grey_overlay_is_dropped_and_not_read_as_text(pdf_path):
    lines = sum((question_lines(n, None) for n in range(1, 4)), [])
    items, _ = flow(lines, 60, 60)
    overlay = [(40 + 80 * i, 180 + 90 * i, 6, "overlaywatermark@mail.com", 0.22) for i in range(6)]
    (questions, warnings), _ = read(pdf_path, make_pdf([items + overlay]))
    blob = " ".join(q["text"] + q["option_a"] + q["option_b"] + q["option_c"] + q["option_d"] for q in questions)
    assert warnings == []
    assert [q["question_number"] for q in questions] == [1, 2, 3]
    assert "overlaywatermark" not in blob and "mail.com" not in blob


def test_script_gutter_splits_hindi_left_from_english_right():
    words = ([{"text": "\u0915\u0925\u0928", "x0": 40, "x1": 80}] * 16
             + [{"text": "Which", "x0": 320, "x1": 380}] * 16)
    g = te.script_gutter_from_words(words, 595)
    assert g is not None and 80 < g < 320


def test_script_gutter_is_none_on_an_english_only_page():
    words = [{"text": "Consider", "x0": 50 + (i % 3) * 80, "x1": 120 + (i % 3) * 80} for i in range(30)]
    assert te.script_gutter_from_words(words, 595) is None


def test_a_question_that_continues_in_the_next_column_is_joined(pdf_path):
    (questions, _), _ = read(pdf_path, paper_pdf(20))
    split = [q for q in questions if q["page_number"] and "item" in q["text"]]
    for q in questions:
        n = q["question_number"]
        assert f"item {n}" in q["text"] and q["option_c"] == "Both 1 and 2" and q["option_d"] == "Neither 1 nor 2", n
    assert len(split) == 20


# --------------------------------------------------------------------------- answers printed under the questions

def test_inline_answers_and_explanations_are_captured(pdf_path):
    (questions, _), _ = read(pdf_path, paper_pdf(20))
    assert "".join(q["answer"] for q in questions) == "ABCD" * 5
    assert questions[6]["explanation"] == "Explanation for item 7 is here and it wraps as well."
    assert all("Answer" not in q["option_d"] for q in questions)             # the answer line never lands in option (d)
    assert all(not q["flags"] for q in questions)


def test_an_answer_line_in_either_spelling_is_read(pdf_path):
    (questions, _), _ = read(pdf_path, paper_pdf(4))
    assert [q["answer"] for q in questions] == ["A", "B", "C", "D"]         # 'Answer-(a)' on odd, 'Answer: (b)' on even


def test_an_unreadable_answer_is_flagged_not_guessed(pdf_path):
    (questions, _), _ = read(pdf_path, paper_pdf(6, unclear=True))
    assert all(q["answer"] is None and "answer_unclear" in q["flags"] for q in questions)
    assert all(q["explanation"] for q in questions)                          # the explanation is still captured


def test_a_question_without_an_answer_line_is_flagged(pdf_path):
    lines = sum((question_lines(n, answer=None if n == 2 else "ABCD") for n in range(1, 6)), [])
    items, _ = flow(lines, LEFT_X, 70)
    (questions, _), _ = read(pdf_path, make_pdf([items]))
    assert [q["question_number"] for q in questions] == [1, 2, 3, 4, 5]
    assert [q["answer"] for q in questions] == ["A", None, "C", "D", "A"]
    assert "no_answer_found" in questions[1]["flags"] and not questions[0]["flags"] and not questions[2]["flags"]


def test_a_paper_without_printed_answers_gives_questions_only(pdf_path):
    (questions, warnings), _ = read(pdf_path, paper_pdf(20, with_answers=False))
    assert len(questions) == 20 and warnings == []
    assert all(q["answer"] is None and q["explanation"] is None and not q["flags"] for q in questions)
    assert all(q["option_d"] == "Neither 1 nor 2" for q in questions)


# --------------------------------------------------------------------------- layouts

def test_a_single_column_paper_is_read_as_one_column(pdf_path):
    lines = sum((question_lines(n, None) for n in range(1, 4)), [])
    items, _ = flow(lines, 60, 60)
    (questions, warnings), _ = read(pdf_path, make_pdf([items]))
    assert [q["question_number"] for q in questions] == [1, 2, 3] and warnings == []


def test_the_one_column_setting_never_splits_a_page(pdf_path):
    data = paper_pdf(6)
    path = pdf_path(data)
    import pdfplumber
    with pdfplumber.open(path) as pdf:
        page = te._cleaned(pdf.pages[1])                        # without the giant watermark that fills the gap
        assert te.find_gutter(page, "auto") is not None
        assert te.find_gutter(page, "one") is None
        assert 290 <= te.find_gutter(page, "two") <= 330


def test_the_gutter_is_found_in_the_gap_between_columns(pdf_path):
    import pdfplumber
    with pdfplumber.open(pdf_path(paper_pdf(6))) as pdf:
        g = te.find_gutter(te._cleaned(pdf.pages[1]), "auto")
    assert 290 <= g <= 330


# --------------------------------------------------------------------------- snapshots

def test_each_question_gets_a_snapshot_that_stops_before_the_answer(pdf_path):
    from PIL import Image
    (questions, _), images = read(pdf_path, paper_pdf(8))
    assert all(q["source_image"] == f"q{q['question_number']}.jpg" for q in questions)
    q1 = Image.open(os.path.join(images, "q1.jpg"))
    # 7 printed lines (question, 2 statements + wrap, 'Which...', 2 option lines): 6 gaps of 14 pt plus one 10 pt line,
    # padding each side, drawn at 2x. The answer line right below would add another 28 px.
    expected_height = int(((6 * 14 + 10) + 2 * te.SNAPSHOT_PAD) * te.SNAPSHOT_SCALE)
    assert abs(q1.height - expected_height) <= 10, (q1.height, expected_height)
    assert q1.width > 300


def test_a_question_split_across_columns_is_stacked_into_one_snapshot(pdf_path):
    from PIL import Image
    (questions, _), images = read(pdf_path, paper_pdf(20))
    heights = {q["question_number"]: Image.open(os.path.join(images, q["source_image"])).height for q in questions}
    # Each question is 10 printed lines (7 + answer + 2 of explanation) and a column holds 25; the 7 lines of question and
    # options cross a column break for these:
    crossing = {n for n in range(1, 21) if (10 * (n - 1)) // COLUMN_LINES != (10 * (n - 1) + 6) // COLUMN_LINES}
    assert crossing == {3, 8, 13, 18}
    whole = min(heights.values())
    assert {n for n, h in heights.items() if h > whole + 5} == crossing          # two pieces stacked: a little taller
    assert all(h <= whole + 30 for h in heights.values())


# --------------------------------------------------------------------------- failure modes

def test_a_text_pdf_with_no_questions_says_so(pdf_path):
    items, _ = flow(["This is a page of ordinary prose.", "It has no numbered questions at all,", "just sentences."] * 20, 60, 60)
    (questions, warnings), _ = read(pdf_path, make_pdf([items]))
    assert questions == [] and "No questions were found" in warnings[0]


def test_a_question_whose_options_were_lost_swallows_the_next_and_is_reported(pdf_path):
    lines = ["1. A question whose options were lost", "(a) only one option here"] + question_lines(2, None)
    items, _ = flow(lines, 60, 60)
    (questions, warnings), _ = read(pdf_path, make_pdf([items]))
    assert [q["question_number"] for q in questions] == [1]                   # nothing after it could start a question
    assert "maybe_merged" in questions[0]["flags"]
    assert any("look like two questions merged" in w and "1" in w for w in warnings)


def test_a_misprinted_number_after_options_still_starts_the_next_question(pdf_path):
    """Coaching PDFs sometimes reprint the wrong number (25. instead of 27.) once the previous options end."""
    lines = question_lines(1, None) + [
        "25. Consider the following pairs:",
        "(a) one pair (b) two pairs",
        "(c) three pairs (d) all four pairs",
    ]
    items, _ = flow(lines, 60, 60)
    (questions, warnings), _ = read(pdf_path, make_pdf([items]))
    assert [q["question_number"] for q in questions] == [1, 2]
    assert questions[1]["text"].startswith("Consider the following pairs:")
    assert questions[1]["option_a"] == "one pair"
    assert warnings == []


def test_a_question_with_fewer_than_four_options_is_flagged(pdf_path):
    items, _ = flow(["1. A question with two options", "(a) first (b) second"], 60, 60)
    (questions, warnings), _ = read(pdf_path, make_pdf([items]))
    assert "options_not_found" in questions[0]["flags"]
    assert any("Options (a)-(d) weren't found" in w for w in warnings)


def test_hindi_text_is_flagged(pdf_path):
    items, _ = flow(["1. Which is the capital of India?", "(a) Delhi (b) Mumbai", "(c) Kolkata (d) Chennai"], 60, 60)
    (questions, _), _ = read(pdf_path, make_pdf([items]))
    assert not questions[0]["flags"]
    q = te._question_from({"number": 1, "answer": None, "answer_seen": False, "explanation": [], "body": [
        {"text": "1. भारत की राजधानी?", "page": 0},
        {"text": "(a) a (b) b (c) c (d) d", "page": 0}]}, None)
    assert "hindi_text" in q["flags"]


def test_lists_and_tables_are_flagged_for_a_second_look(pdf_path):
    items, _ = flow(["1. Match List-I with List-II:", "A. Alpha 1. First", "B. Beta 2. Second",
                     "(a) 1 2 (b) 2 1", "(c) 1 1 (d) 2 2"], 60, 60)
    (questions, _), _ = read(pdf_path, make_pdf([items]))
    assert "check_table" in questions[0]["flags"]
    assert questions[0]["text"].splitlines()[0].startswith("Match List-I")
    assert "A. Alpha 1. First" in questions[0]["text"].splitlines()


# --------------------------------------------------------------------------- the pure pieces

def test_split_options_takes_the_last_marker_sequence():
    stem, options = te.split_options("Assertion (a) is stated. Choose:\n(a) one (b) two\n(c) three\n(d) four")
    assert stem.startswith("Assertion (a) is stated.") and options == ["one", "two", "three", "four"]
    assert te.split_options("(a) only (b) two (c) three") is None
    assert te.split_options("(a) x (c) y (b) z (d) w") is None              # markers out of order aren't a set of options


def test_paragraph_joining_keeps_list_items_on_their_own_lines():
    lines = ["Consider the following", "statements:", "1. First item", "which wraps.", "2. Second item", "Which of them is right?"]
    assert te._paragraphs(lines) == "Consider the following statements:\n1. First item which wraps.\n2. Second item\nWhich of them is right?"


# =========================================================================== through the upload page and ingest

def form(title, **extra):
    return {"title": title, "exam_type": "full_length", "source_type": "coaching_test", **extra}


def pdf_files(question_pdf: bytes, answer_pdf: bytes | None = None):
    files = {"pdf_file": ("q.pdf", question_pdf, "application/pdf")}
    if answer_pdf is not None:
        files["answer_file"] = ("a.pdf", answer_pdf, "application/pdf")
    return files


def paper_named(db, title):
    db.rollback()
    return db.query(models.Paper).filter_by(title=title).one()


def questions_of(db, paper):
    db.rollback()
    return {q.question_number: q for q in db.query(models.Question).filter_by(paper_id=paper.id)}


@pytest.fixture()
def no_tesseract(monkeypatch):
    """Pretend OCR isn't installed: a text PDF must still import."""
    from app import ocr_extract

    def missing():
        raise ocr_extract.OcrUnavailable("Tesseract is not installed (test).")
    monkeypatch.setattr(ocr_extract, "tesseract_cmd", missing)


def test_a_text_pdf_imports_without_tesseract_and_is_marked_as_read_from_text(admin, db, no_tesseract):
    r = admin.post("/upload", data=form("Text route paper", year="2026"), files=pdf_files(paper_pdf(20)))
    assert r.status_code == 303
    paper = paper_named(db, "Text route paper")
    assert paper.status == "ready" and paper.status_message is None
    qs = questions_of(db, paper)
    assert sorted(qs) == list(range(1, 21))
    q = qs[7]
    assert (q.source, q.extraction_method, q.answer_source, q.status) == ("pdf_text", "text", "inline", models.QStatus.NEEDS_REVIEW)
    assert q.correct_answer == "C" and q.explanation == "Explanation for item 7 is here and it wraps as well."
    assert q.explanation_status == "unverified" and q.page_number >= 2 and not (q.ocr_flags or "").replace("source_conflict", "")     # (the shared test database holds other papers printing the same questions)
    assert q.option_c == "Both 1 and 2" and q.source_image_path == "q7.jpg"
    from app import ingest
    assert os.path.exists(os.path.join(ingest.images_dir_for(paper.id), "q7.jpg"))
    entry = db.query(models.AuditLog).filter_by(action="paper.import_done", paper_id=paper.id).one()
    assert '"method": "text"' in entry.detail_json and '"answers_printed_in_paper": 20' in entry.detail_json


def test_imported_questions_wait_for_review_and_cannot_go_live_untouched(admin, db, no_tesseract):
    admin.post("/upload", data=form("Text review gate paper"), files=pdf_files(paper_pdf(20)))
    paper = paper_named(db, "Text review gate paper")
    from app.practice import pool
    assert pool.live_questions(db).filter(models.Question.paper_id == paper.id).count() == 0
    admin.post(f"/papers/{paper.id}/publish")
    db.rollback()
    assert db.get(models.Paper, paper.id).publish_status != "published"          # every question still needs confirming


def test_the_review_page_shows_flags_from_the_text_reader(admin, db, no_tesseract):
    lines = sum((question_lines(n, answer=None if n == 2 else "ABCD") for n in range(1, 6)), [])
    items, _ = flow(lines, LEFT_X, 70)
    admin.post("/upload", data=form("Text flags paper"), files=pdf_files(make_pdf([items])))
    paper = paper_named(db, "Text flags paper")
    page = admin.get(f"/review/{paper.id}").text
    assert "No answer supplied or found" in page
    assert questions_of(db, paper)[2].correct_answer is None and questions_of(db, paper)[1].correct_answer == "A"


def test_a_separate_answer_key_wins_and_a_disagreement_is_flagged(admin, db, no_tesseract):
    lines = sum((question_lines(n) for n in range(1, 6)), [])                 # printed answers: A B C D A
    items, _ = flow(lines, LEFT_X, 70)
    key_items, _ = flow(["1. Ans- (b)", "2. Ans- (b)", "3. Ans- (c)"], 60, 100)        # disagrees on 1; silent on 4 and 5
    r = admin.post("/upload", data=form("Text key paper"), files=pdf_files(make_pdf([items]), make_pdf([key_items])))
    assert r.status_code == 303
    qs = questions_of(db, paper_named(db, "Text key paper"))
    assert (qs[1].correct_answer, qs[1].answer_source) == ("B", "key_pdf") and "answer_conflict" in qs[1].ocr_flags
    assert (qs[2].correct_answer, qs[2].answer_source) == ("B", "key_pdf") and not (qs[2].ocr_flags or "").replace("source_conflict", "")
    assert (qs[4].correct_answer, qs[4].answer_source) == ("D", "inline") and "no_answer_in_key" in qs[4].ocr_flags


def test_a_paper_that_finds_a_different_number_of_questions_than_expected_says_so(admin, db, no_tesseract):
    admin.post("/upload", data=form("Text count paper", expected_total="25"), files=pdf_files(paper_pdf(20)))
    assert "Found 20 questions but you expected 25." in paper_named(db, "Text count paper").status_message
    admin.post("/upload", data=form("Text count ok paper", expected_total="20"), files=pdf_files(paper_pdf(20, explanation=False)))
    assert paper_named(db, "Text count ok paper").status_message is None


def test_a_scan_still_needs_tesseract_and_says_so_before_creating_anything(admin, db, no_tesseract):
    before = db.query(models.Paper).count()
    r = admin.post("/upload", data=form("Scan without OCR paper"), files=pdf_files(blank_pdf_bytes(pages=2)))
    assert r.status_code == 400 and "Tesseract is not installed" in r.text
    db.rollback()
    assert db.query(models.Paper).count() == before
    assert not [f for f in os.listdir(os.path.join(os.environ["UPSC_DATA_DIR"], "pdfs")) if "Scan" in f]


def test_the_layout_choice_is_offered_and_validated(admin, db, no_tesseract):
    page = admin.get("/upload").text
    assert 'name="layout"' in page and "Auto-detect" in page and "One column" in page and "Two columns" in page
    r = admin.post("/upload", data=form("Bad layout paper", layout="diagonal"), files=pdf_files(paper_pdf(6)))
    assert r.status_code == 400 and "page layout" in r.text.lower()
    assert admin.post("/upload", data=form("Two column paper", layout="two"), files=pdf_files(paper_pdf(20))).status_code == 303
    assert len(questions_of(db, paper_named(db, "Two column paper"))) == 20


def test_a_text_pdf_that_yields_no_questions_falls_back_to_ocr_and_says_so(admin, db):
    from app import ocr_extract
    try:
        ocr_extract.tesseract_cmd()
    except ocr_extract.OcrUnavailable:
        pytest.skip("Tesseract isn't installed")
    prose, _ = flow(["This is a page of ordinary prose without any questions in it at all,"] * 30, 60, 60)
    r = admin.post("/upload", data=form("Prose fallback paper"), files=pdf_files(make_pdf([prose, prose, prose])))
    assert r.status_code == 303
    paper = paper_named(db, "Prose fallback paper")
    assert "No questions were found in the text of this PDF" in paper.status_message and "Fell back to OCR" in paper.status_message


def test_read_questions_picks_the_method(pdf_path):
    from app import ingest
    text_questions, _, method = ingest.read_questions(pdf_path(paper_pdf(8)), os.path.join(os.environ["UPSC_DATA_DIR"], "m1"))
    assert method == "text" and len(text_questions) == 8


def test_a_bilingual_coaching_pdf_keeps_english_and_drops_the_hindi_column(tmp_path):
    """The RTM-style paper that was uploaded locally: Hindi left, English right, grey email overlays.
    Without the bilingual split the reader found 4 merged questions instead of 75."""
    from glob import glob
    from app.database import BASE_DIR
    matches = glob(os.path.join(BASE_DIR, "data", "pdfs", "*questions*.pdf"))
    if not matches:
        pytest.skip("no uploaded question PDF in data/pdfs")
    path = max(matches, key=os.path.getmtime)
    questions, warnings = te.extract_questions(path, str(tmp_path / "images"))
    assert len(questions) >= 50, (len(questions), warnings[:3])
    q1 = next(q for q in questions if q["question_number"] == 1)
    assert "hindi_text" not in q1["flags"]
    assert "maybe_merged" not in q1["flags"]
    assert not te.DEVANAGARI.search(q1["text"] + q1["option_a"])
    assert "Which" in q1["text"] or "which" in q1["text"] or q1["option_a"]
